---
# https://next.yarnpkg.com/configuration/yarnrc

packageExtensions:
    '@vue/cli-service@*':
        dependencies:
            vue-cli-plugin-pnp: '>=1.0.0'
    'vue-eslint-parser@*':
        dependencies:
            babel-eslint: '>=10.0.3'
